Add warning for transfer larger than CCTP max transfer limit (1M)
wormhole-foundation/wormhole-connect pull request #1682
Opened 2024-02-19 13:07 UTC by yuli-ferna

Issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1504

Result:
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/35125931/b19eaba9-584a-4d8f-932b-b4bca6b2113c)

2024-02-19 16:44 UTC, sebastianscatularo requested changes

2024-02-19 16:44 UTC, sebastianscatularo commented on wormhole-connect/src/utils/transferValidation.ts
> +    return 'Your transaction exceeds the maximum transfer limit of 1,000,000 USDC. Please use a different amount.';
would be good to get the amount from the constant and format, so, if we need to change the amount, we just need to change the const value

2024-02-19 17:21 UTC, yuli-ferna commented on wormhole-connect/src/utils/transferValidation.ts
> +    return 'Your transaction exceeds the maximum transfer limit of 1,000,000 USDC. Please use a different amount.';
Done!

2024-02-27 17:24 UTC, sebastianscatularo approved these changes

2024-02-27 18:11 UTC, merged