Added legal disclaimers
wormhole-foundation/wormhole-connect pull request #1820
Opened 2024-03-21 22:47 UTC by prototypo

2024-03-22 06:51 UTC, kcsongor requested changes

2024-03-22 06:51 UTC, kcsongor commented on LEGAL.txt
> +are available on an “AI IS” basis without warranties of any kind, either express or
```suggestion
are available on an “AS IS” basis without warranties of any kind, either express or
```

2024-03-25 14:46 UTC, artursapek approved these changes
lgtm, feel free to merge!

2024-03-25 14:47 UTC, artursapek approved these changes

2024-03-25 19:13 UTC, prototypo commented
Any wording changes require legal review. I've integrated this feedback into a list for all repositories (since they all need to be consistent). I'll drop this PR for now and submit a new one with any eventual changes.

2024-03-25 19:13 UTC, closed without merging