Do not render widget when no token config found
wormhole-foundation/wormhole-connect pull request #3056
Opened 2024-12-10 13:49 UTC by emreboga

This is a very unlikely case unless a user tempers with the localStorage entry. It was discovered while testing Portal with an invalid localStorage entry. To fix this potential problem we are adding another layer of check to filter out the entries with no token configs.

2024-12-10 14:15 UTC, emreboga commented on wormhole-connect/src/views/v2/Bridge/ReviewTransaction/GasSlider.tsx
> -    console.log(tokenAmount);
This one was creating some noise in the console when in Review Transaction view. Please let me know if you think it'd still be useful when debugging.

2025-02-05 14:09 UTC, artursapek requested changes

2025-02-05 14:09 UTC, artursapek commented on wormhole-connect/src/views/v2/TxHistory/Widget/Item.tsx
> +  const tokenConfig = config.tokens.get(tokenTuple);
can we stop using the term "token config"? just keep this as-is.

2025-02-05 14:09 UTC, artursapek commented on wormhole-connect/src/views/v2/TxHistory/Widget/index.tsx
> +    // Filter out the ones with unknown token configs
again, please don't call them token configs. they're just tokens.

2025-02-05 14:09 UTC, artursapek commented on wormhole-connect/src/views/v2/TxHistory/Widget/index.tsx
> +        return !!config.tokens.get(tx?.txDetails?.token);
There's a better way to handle this edge case. If there's a pending tx, then I think we can safely assume the token it refers to exist. And if that's true, and they are not in the token cache, you should just `getOrFetchToken` them here. You can ignore the result - just kick it off and the `TokensContext` will fetch the token and put it in the cache in the background. [See this for example](https://github.com/wormhole-foundation/wormhole-connect/blob/development/wormhole-connect/src/views/v2/Bridge/AssetPicker/TokenList.tsx#L77).

This way you don't have to filter this thing out, you can render it properly once that fetch is complete.

You'll probably need to handle the "loading" case in the meantime where the token is not yet in the cache... maybe just render a `Skeleton`. And re-render once the cache is updated (which you can do by depending on `lastTokenCacheUpdate` [like here](https://github.com/wormhole-foundation/wormhole-connect/blob/development/wormhole-connect/src/views/v2/Bridge/index.tsx#L323))

2025-02-05 15:50 UTC, emreboga commented on wormhole-connect/src/views/v2/TxHistory/Widget/index.tsx
> +        return !!config.tokens.get(tx?.txDetails?.token);
Thanks for the recommendation, but it has the assumption that the token is among the supported ones. The need for this check came in after I learnt that Portal QA team has a test case to make sure Connect is not broken after user tempers with the local storage entry. In that case it doesn't matter whether we fetch the token.
This is still a very edge case, but I still wanted to added.

2025-02-05 15:54 UTC, emreboga commented on wormhole-connect/src/views/v2/TxHistory/Widget/Item.tsx
> +  const tokenConfig = config.tokens.get(tokenTuple);
https://github.com/wormhole-foundation/wormhole-connect/pull/3056/commits/e84f5c3817342ff641d038b9f3934c940db55db4

2025-02-05 15:55 UTC, emreboga commented on wormhole-connect/src/views/v2/TxHistory/Widget/index.tsx
> +    // Filter out the ones with unknown token configs
https://github.com/wormhole-foundation/wormhole-connect/pull/3056/commits/e84f5c3817342ff641d038b9f3934c940db55db4

2025-02-05 16:01 UTC, artursapek commented on wormhole-connect/src/views/v2/TxHistory/Widget/index.tsx
> +        return !!config.tokens.get(tx?.txDetails?.token);
OK. Fine with me. Unlikely the non-tamper case would ever happen to begin with anyway

2025-02-05 16:02 UTC, artursapek approved these changes

2025-02-05 16:54 UTC, merged