fix: The sol icon is replaced with base64
wormhole-foundation/wormhole-connect pull request #3106
Opened 2024-12-23 07:20 UTC by friendlysxw

2024-12-23 16:52 UTC, emreboga commented
Hey @friendlysxw , thanks for the PR! I looked into this and not 100% sure if the icon problem is due to multiple Solana svgs having same id `LinearGradient` elements. Yes, you will have multiple html elements of the same id, which is not ideal; but these elements with same ids are essentially the same elements. Whichever one browser picks when referred by `url(#element_id)` will result in the same look. You can see this in PortalBridge as well. Those Solana icons all have duplicate LinearGradient elements, but still render fine:
<img width="521" alt="Screenshot 2024-12-23 at 7 38 20 PM" src="https://github.com/user-attachments/assets/ca8aa1b1-e9b1-418f-9362-6ffd257e19e9" />

Do you get any warnings/errors in the browser console regarding this? Which browser version are you using?

2024-12-25 07:26 UTC, friendlysxw commented
> 嘿@friendlysxw，感谢 PR！我研究了这个问题，但不能 100% 确定图标问题是否是由于多个 Solana svg 具有相同的 id`LinearGradient`元素造成的。是的，您将拥有多个具有相同 id 的 html 元素，这并不理想；但这些具有相同 id 的元素本质上是相同的元素。无论浏览器在引用时选择哪一个，`url(#element_id)`都会产生相同的外观。您也可以在 PortalBridge 中看到这一点。这些 Solana 图标都有重复的 LinearGradient 元素，但仍然可以正常渲染： <img alt="截图 2024-12-23 下午 7 点 38 分 20 秒" width="521" src="https://private-user-images.githubusercontent.com/10507890/398214426-ca8aa1b1-e9b1-418f-9362-6ffd257e19e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzczMjUsIm5iZiI6MTczNTAzNzAyNSwicGF0aCI6Ii8xMDUwNzg5MC8zOTgyMTQ0MjYtY2E4YWExYjEtZTliMS00MThmLTkzNjItNmZmZDI1N2UxOWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDEwNDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZDRlYTAyNjU4MzYxNTI4YjFmY2I3MzQyNGEyYzNkZDY0ODFiNWU2MjJkNjJlNmRlMWMwMWU4ZmJmZTkwMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RooBWQkrkz1CS4f3gZbtHHlPv3ZdUUfVZKaifuIqeZA">
> 
> 您在浏览器控制台中收到与此相关的任何警告/错误吗？您使用的是哪个浏览器版本？

No errors and related alerts in the consoleChrome/131.0.0.0

2024-12-25 07:59 UTC, friendlysxw commented
> 嘿@friendlysxw，感谢PR！我研究了这个问题，但不能100%确定图标问题是否是由于多个Solana svg具有相同的id`LinearGradient`元素造成的。是的，您将拥有多个具有相同id的html元素，这并不是理想；但具有这些相同id的元素本质上是相同的元素。无论浏览器在引用时选择哪一个，`url(#element_id)`都会产生相同的外观。您也可以在PortalBridge中看到这一点。这些Solana图标都有重复的LinearGradient元素，但仍然可以正常渲染： <img alt="截图2024-12-23下午7点38分20秒" width="521" src="https://private-user-images.githubusercontent.com/10507890/398214426-ca8aa1b1-e9b1-418f-9362-6ffd257e19e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzczMjUsIm5iZiI6MTczNTAzNzAyNSwicGF0aCI6Ii8xMDUwNzg5MC8zOTgyMTQ0MjYtY2E4YWExYjEtZTliMS00MThmLTkzNjItNmZmZDI1N2UxOWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDEwNDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZDRlYTAyNjU4MzYxNTI4YjFmY2I3MzQyNGEyYzNkZDY0ODFiNWU2MjJkNjJlNmRlMWMwMWU4ZmJmZTkwMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RooBWQkrkz1CS4f3gZbtHHlPv3ZdUUfVZKaifuIqeZA">
> 
> 您在浏览器控制台中收到此相关的任何警告/错误吗？您使用的是哪个浏览器版本？


The possible issue is that there is an element with the same id in my project but with a different style, and I couldn't find any elements other than the SOL icon in this repository using `document.querySelectorAll("#paint0_linear_85_9551")`, which also confuses me a bit...
Oh, yes.

The styles of the elements corresponding to url(#element_id) are the same, which is indeed not a problem in the demo.

The only way I can currently solve this problem is to replace the SVGs with id attributes in this repository with other image formats, or to ensure that the ids in the SVGs are unique.

2024-12-25 08:00 UTC, friendlysxw commented
> 嘿@friendlysxw，感谢PR！我研究了这个问题，但不能100%确定图标问题是否是由于多个Solana svg 具有相同id`LinearGradient`的元素造成的多个。是的，您将拥有具有相同id 的html 元素，这不是理想的；但这些相同id 的元素本质上是具有相同的元素。浏览器在引用时选择其中一个，`url(#element_id)`都会产生相同的外观。您也可以在PortalBridge中看到这一点。这些Solana图标都有重复的LinearGradient元素，但仍然可以正常渲染： <img alt="截图2024-12-23下午7点38分20秒" width="521" src="https://private-user-images.githubusercontent.com/10507890/398214426-ca8aa1b1-e9b1-418f-9362-6ffd257e19e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzczMjUsIm5iZiI6MTczNTAzNzAyNSwicGF0aCI6Ii8xMDUwNzg5MC8zOTgyMTQ0MjYtY2E4YWExYjEtZTliMS00MThmLTkzNjItNmZmZDI1N2UxOWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDEwNDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZDRlYTAyNjU4MzYxNTI4YjFmY2I3MzQyNGEyYzNkZDY0ODFiNWU2MjJkNjJlNmRlMWMwMWU4ZmJmZTkwMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RooBWQkrkz1CS4f3gZbtHHlPv3ZdUUfVZKaifuIqeZA">
> 
> 您在浏览器控制台中收到此相关的任何警告/错误吗？您使用的是哪个浏览器版本？

Oh, yes.
The styles of the elements corresponding to url(#element_id) are the same, which is indeed not a problem in the demo.

The possible issue is that there is an element with the same id in my project but with a different style, and I couldn't find any elements other than the SOL icon in this repository using `document.querySelectorAll("#paint0_linear_85_9551")`, which also confuses me a bit...

The only way I can currently solve this problem is to replace the SVGs with id attributes in this repository with other image formats, or to ensure that the ids in the SVGs are unique.

2025-01-07 22:11 UTC, artursapek requested changes
thanks for the PR, but we want to stay on SVG for all our icons. is there another solution that keeps it as an SVG?

2025-01-16 12:46 UTC, closed without merging

2025-01-16 12:46 UTC, aadam-10 commented
closing this pr to keep the queue clean. @friendlysxw please let us know if you have updates and we can reopen it.